name: ecommerce
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  equatable: ^0.2.0
  flutter_bloc: ^3.2.0
  cached_network_image: ^2.0.0
  font_awesome_flutter: 8.8.1
  flutter_swiper: 1.1.6
  flutter_custom_clippers: 1.1.0
  countdown_flutter: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/app-icon.jpg
    - assets/data/posts.json
    - assets/data/post.json
    - assets/data/post1.json
    - assets/data/post2.json
    - assets/data/post3.json
    - assets/data/post4.json
    - assets/data/post5.json
    - assets/data/post6.json
    - assets/data/post7.json
    - assets/data/post8.json
    - assets/data/post9.json
    - assets/data/post10.json
    - assets/data/post11.json
    - assets/data/post12.json
    - assets/data/post13.json

    - assets/data/category1.json
    - assets/data/category2.json
    - assets/data/category3.json
    - assets/data/category4.json
    - assets/data/category5.json

    - assets/data/popular_listing.json
    - assets/data/all_posts.json

    - assets/data/wish_items.json
    - assets/data/search.json
    - assets/data/order_items.json

    - assets/order-success.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
